[package]
name = "lumberjack"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
color-eyre = "0.6.3"
crossterm = "0.29.0"
derive-new = "0.7.0"
itertools = "0.14.0"
ratatui = { version = "0.29.0", features = ["serde", "widget-calendar"] }
regex = "1.11.1"
unicode-width = "0.2.0"
